/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Usuario.ArregloCliente;
import administrador.ArregloAdmin;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class adminCon extends javax.swing.JFrame {
ArregloCliente arreglocliente;
ArregloAdmin arregloadmin;
private ImageIcon imagen;
private Icon icono;

    /**
     * Creates new form adminCon
     */
    public adminCon(ArregloCliente arreglocliente,ArregloAdmin arregloadmin) {
        this.arregloadmin = arregloadmin;
        this.arreglocliente = arreglocliente;
        initComponents();
        this.pintarImagen(this.photo, "src/imagen/minipekka.jpg");
        this.setLocationRelativeTo(null);
        this.setTitle("Controlador pa admin chikititito");
        this.setResizable(false);//desactiva la opcion de modificar el tamaño una vez ejecutado el JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminUsuario = new javax.swing.JButton();
        btnAdminInven = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnAdminSistem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminUsuario.setText(" Usuarios");
        btnAdminUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdminUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 255, 130, 44));

        btnAdminInven.setText("Inventario");
        getContentPane().add(btnAdminInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 130, 38));

        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 130, 45));

        btnAdminSistem.setText("Admin. Sistema");
        btnAdminSistem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSistemActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdminSistem, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 177, 130, 46));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("GESTION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 580, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminUsuarioActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        TipoAdmin tipoadmin= new TipoAdmin(this.arreglocliente,this.arregloadmin);
        tipoadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAdminSistemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSistemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminSistemActionPerformed
private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminInven;
    private javax.swing.JButton btnAdminSistem;
    private javax.swing.JButton btnAdminUsuario;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel photo;
    // End of variables declaration//GEN-END:variables
}
