/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Usuario.ArregloCliente;
import administrador.ArregloAdmin;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class admin extends javax.swing.JFrame {
ArregloCliente arreglocliente;
ArregloAdmin arregloadmin;
private ImageIcon imagen;
    private Icon icono;
    /**
     * Creates new form admin
     */
    public admin(ArregloCliente arreglocliente,ArregloAdmin arregloadmin) {
        initComponents();
        this.arregloadmin = arregloadmin;
        this.arreglocliente = arreglocliente;
        this.setLocationRelativeTo(null);
        this.setTitle("Login de admin chikito");
        this.pintarImagen(this.lblImage1, "src/imagen/perfildeusuario.jpg");
        this.pintarImagen(this.lblImage2, "src/imagen/contra.png");
        this.pintarImagen(this.photo, "src/imagen/catKing.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        pswContra = new javax.swing.JPasswordField();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 153, -1));

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 110, 30));

        btnLogin.setText("Logearse");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 110, 30));
        getContentPane().add(pswContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 150, -1));

        lblImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage1.setOpaque(true);
        getContentPane().add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 30, 30));

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perfildeusuario.jpg"))); // NOI18N
        lblImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage2.setOpaque(true);
        getContentPane().add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 30, 30));
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        TipoAdmin tipoadmin = new TipoAdmin(this.arreglocliente,this.arregloadmin);
        tipoadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String usuario, contraseña;

        usuario = this.txtUsuario.getText();
        contraseña = String.valueOf(this.pswContra.getPassword());

        if(arregloadmin.VerificaLogeo(usuario,contraseña)){
            adminCon ingresar = new adminCon(this.arreglocliente,this.arregloadmin);
            JOptionPane.showMessageDialog(this, "Hola");
            ingresar.setVisible(true);
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(this, "Keep trying");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel photo;
    private javax.swing.JPasswordField pswContra;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
