/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import ControladorAdmin.config;
import Usuario.ArregloCliente;
import administrador.ArregloAdmin;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.IconUIResource;

/**
 *
 * @author ssant
 */
public class Administrador extends javax.swing.JFrame {
    private ImageIcon imagen;
    private Icon icono;
    ArregloCliente arreglocliente;
    ArregloAdmin arregloadmin;
    /**
     * Creates new form Administrador
     */
    public Administrador(ArregloCliente arreglocliente, ArregloAdmin arregloadmin) {
        this.arregloadmin=arregloadmin;
        this.arreglocliente = arreglocliente;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Administrador");
        
        this.pintarImagen(this.lblImage1, "src/imagen/perfildeusuario.jpg");
        this.pintarImagen(this.lblImage2, "src/imagen/contra.png");
        this.setResizable(false);//desactiva la opcion de modificar el tamaño una vez ejecutado el JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        PswContraseña = new javax.swing.JPasswordField();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, -1));

        lblImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage1.setOpaque(true);
        getContentPane().add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 30, 30));

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perfildeusuario.jpg"))); // NOI18N
        lblImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage2.setOpaque(true);
        getContentPane().add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 30, 30));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        PswContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PswContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(PswContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/admin.jpg"))); // NOI18N
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 430, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        TipoAdmin tipoadmin= new TipoAdmin(this.arreglocliente,this.arregloadmin);
        tipoadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String usuario = this.txtUsuario.getText();
        String contraseña = String.valueOf(this.PswContraseña.getPassword());
        if(usuario.equalsIgnoreCase(config.loginUser)&&contraseña.equalsIgnoreCase(config.loginPass)){
        AdminControl admincontrol = new AdminControl(this.arreglocliente,this.arregloadmin);
        admincontrol.setVisible(true);
        this.dispose();
        }
        else{
        this.txtUsuario.setText("");
        this.PswContraseña.setText("");
        JOptionPane.showMessageDialog(this,"Admin Incorrecto");
        }            
        
        
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void PswContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PswContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PswContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PswContraseña;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
