/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Usuario.ArregloCliente;
import administrador.ArregloAdmin;

/**
 *
 * @author ssant
 */
public class PerUsu extends javax.swing.JFrame {
ArregloCliente arreglocliente;
ArregloAdmin  arregloadmin;
    /**
     * Creates new form PerUsu
     */
    public PerUsu(ArregloCliente arreglocliente,ArregloAdmin  arregloadmin) {
        this.arreglocliente = arreglocliente;
        this.arregloadmin = arregloadmin;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Perfil de Usuario");
        this.setResizable(false);//desactiva la opcion de modificar el tamaño una vez ejecutado el JFrame
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRCita = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRCita.setText("Sacar Cita");
        btnRCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRCitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jButton4.setText("Cerrar sesion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jButton1.setText("Obras");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Usuario volver = new Usuario(this.arreglocliente,this.arregloadmin);
        volver.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRCitaActionPerformed
        
        ReservaCita reservacita = new ReservaCita(this.arreglocliente,this.arregloadmin);
        reservacita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRCita;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
