/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Usuario.ArregloCliente;
import administrador.ArregloAdmin;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class TipoAdmin extends javax.swing.JFrame {
    ArregloCliente arreglocliente;
    ArregloAdmin arregloadmin;
    private ImageIcon imagen;
    private Icon icono; 
    /**
     * Creates new form TipoAdmin
     */
    public TipoAdmin(ArregloCliente arreglocliente,ArregloAdmin arregloadmin) {
        this.arregloadmin =arregloadmin;
        this.arreglocliente = arreglocliente;
        initComponents();
        this.pintarImagen(this.photo, "src/imagen/Godzilla.jpg");
        this.pintarImagen(this.Photo, "src/imagen/Kong.jpg");
        this.setLocationRelativeTo(null);
        this.setTitle("Tipo Administrador");
        this.setResizable(false);//desactiva la opcion de modificar el tamaño una vez ejecutado el JFrame
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnGeneral = new javax.swing.JButton();
        btnContrat = new javax.swing.JButton();
        photo = new javax.swing.JLabel();
        Photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tipo Administrador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 383, 80, 30));

        btnGeneral.setText("General");
        btnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(btnGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 31));

        btnContrat.setText("Contratados");
        btnContrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratActionPerformed(evt);
            }
        });
        getContentPane().add(btnContrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 120, 40));

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 270, 360));

        Photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 240, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralActionPerformed
        Administrador administrador = new Administrador(this.arreglocliente,this.arregloadmin);
        administrador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGeneralActionPerformed

    private void btnContratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratActionPerformed
        admin admin1= new admin(this.arreglocliente,this.arregloadmin);
        admin1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContratActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        UsuAdmin usuadmin= new UsuAdmin(this.arreglocliente,this.arregloadmin);
        usuadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Photo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContrat;
    private javax.swing.JButton btnGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel photo;
    // End of variables declaration//GEN-END:variables
}
