/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Usuario.ArregloCliente;
import administrador.ArregloAdmin;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ssant
 */
public class UsuLog extends javax.swing.JFrame {
    ArregloCliente arreglocliente;
    ArregloAdmin arregloadmin;
    private ImageIcon imagen;
    private Icon icono;  
/**
     * Creates new form UsuLog
     */
    public UsuLog(ArregloCliente arreglocliente,ArregloAdmin  arregloadmin) {
        initComponents();
        this.arreglocliente=arreglocliente;
        this.arregloadmin = arregloadmin;
        this.pintarImagen(this.Photo, "src/imagen/RemRamp.jpg");
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
        this.pintarImagen(this.lblImage1, "src/imagen/perfildeusuario.jpg");
        this.pintarImagen(this.lblImage2, "src/imagen/contra.png");
        this.setResizable(false);//desactiva la opcion de modificar el tamaño una vez ejecutado el JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        pswContra = new javax.swing.JPasswordField();
        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        Photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 160, -1));

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 90, 40));

        btnLogin.setText("Logearse");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 90, 40));
        getContentPane().add(pswContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 160, -1));

        lblImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage1.setOpaque(true);
        getContentPane().add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 30, 30));

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perfildeusuario.jpg"))); // NOI18N
        lblImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage2.setOpaque(true);
        getContentPane().add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 30, 30));
        getContentPane().add(Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       String usuario, contraseña;
       
       usuario = this.txtUsuario.getText();
       contraseña = String.valueOf(this.pswContra.getPassword());
       
        if(arreglocliente.VerificaLogeo(usuario,contraseña)){
           PerUsu ingresar = new PerUsu(this.arreglocliente,this.arregloadmin);
           JOptionPane.showMessageDialog(this, "Hola");
           ingresar.setVisible(true);
           this.setVisible(false);
           
       }else{
           JOptionPane.showMessageDialog(this, "Sigue intentando compa");
       }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Usuario volver = new Usuario(this.arreglocliente,this.arregloadmin);
        volver.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed
private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Photo;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JPasswordField pswContra;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
